server:
  port: 8080
  forward-headers-strategy: framework

spring:
  profiles:
    active: dev
  session:
    store-type: redis
    redis:
      namespace: spring:session
      flush-mode: immediate
    timeout: 1440
  jpa:
    show-sql: true
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none # 线上环境谨慎使用其他参数
  datasource:
    write:
      #mysql 配置
      dbType: mysql
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://${mysql-host-write}:${mysql-port-write}/${mysql-database-write}?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: ${mysql-user-write}
      password: ${mysql-psw-write}
      # 驱动配置信息
      type: com.alibaba.druid.pool.DruidDataSource
      # 连接池的配置信息:初始化大小，最小，最大
      initialSize: 10
      minIdle: 5
      maxActive: 100
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      #验证库是否正常sql
      validationQuery: select 'x'
      #空闲时验证，防止连接断开
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    read1:
      #mysql 配置
      dbType: mysql
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://${mysql-host-read1}:${mysql-port-read1}/${mysql-database-read1}?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: ${mysql-user-read1}
      password: ${mysql-psw-read1}
      # 驱动配置信息
      type: com.alibaba.druid.pool.DruidDataSource
      # 连接池的配置信息:初始化大小，最小，最大
      initialSize: 10
      minIdle: 5
      maxActive: 100
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      #验证库是否正常sql
      validationQuery: select 'x'
      #空闲时验证，防止连接断开
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    host: ${redis-host}
    port: ${redis-port}
    database: 0
    jedis:
      pool:
        max-active: 100
        min-idle: 10

logging:
  config: classpath:logback-spring.xml
  file:
    path: ./log/